global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:7072']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8090']

  - job_name: 'spark-workers'
    static_configs:
      - targets: ['spark-worker:8091']

